[package]
name = "nas-notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
libzetta = "0.3.1"
log = "0.4.17"
reqwest = { version = "0.11.14", features = ["blocking", "json"] }
serde = { version = "1.0.154", features = ["derive"] }
simple_logger = "4.0.0"
toml = "0.7.2"
